### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import

### ISSUE THREAD

**Issue by BernardA** [LBrian/content-visibility#7]
When trying to
`import 'content-visibility';`

the following error is thrown:

> Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/bernardo/Sites/soeezauto-client/node_modules/content-visibility/content-visibility.js
require() of ES modules is not supported.
require() of /Users/bernardo/Sites/soeezauto-client/node_modules/content-visibility/content-visibility.js from /Users/bernardo/Sites/soeezauto-client/.next/server/pages/_app.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename content-visibility.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/bernardo/Sites/soeezauto-client/node_modules/content-visibility/package.json.

Thanks

**Comment by LBrian** [comment]
Looks like you are using `Next.js` and I believe currently there are some limitations of server-site rendering webcomponents, I know `dynamic` of `Next.js` can import modules dynamically in browser instead of server site, worth to give it a try otherwise you might need to google it how to SSR webcomponents. Some links for your reference and hopefully it helps.

https://nextjs.org/docs/advanced-features/dynamic-import
https://dev.to/swyx/how-to-use-web-components-with-next-js-and-typescript-4gg1

**Comment by BernardA** [comment]
Thanks, that did work. 

Just a question though: for Chrome, which already adopted `content-visibility`  this does not seem to make a difference. So the benefits of this is to extend or poly-fill for still non-complying browsers. Did I get this right?

**Comment by LBrian** [comment]
> Thanks, that did work.
> 
> Just a question though: for Chrome, which already adopted `content-visibility` this does not seem to make a difference. So the benefits of this is to extend or poly-fill for still non-complying browsers. Did I get this right?

Pretty much but not quite, you are right for other browsers but for Chrome since it supports CSS `content-visibility` so it will just use pure CSS solution instead of using IntersectionObserver
